export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_ERROR = 'SET_ERROR';
export const SET_EMAIL_VALID = 'SET_EMAIL_VALID';
export const SET_EMAIL_ERROR_MESSAGE = 'SET_EMAIL_ERROR_MESSAGE';
export const CLEAR_CREDENTIALS = 'CLEAR_CREDENTIALS';
